name: Linux_IRIS_Scan

on: [push, pull_request]

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
  
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      
      - name: Setup .NET Core 3.1
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '3.1.100'
      - name: Create Settings File
        run: |
            jsonContent=$(jq -n --arg projectId "${{ secrets.PROJECT_ID }}" --arg jwt "${{ secrets.IRIS_JWT }}" \
                        '{projectId: $projectId, jwt_auth: $jwt}')

            echo $jsonContent > iris.settings.json

      - name: Download IRIS Scanner CLI 
        run: | 
          wget -q -O "https://iris.codeeyesolutions.com/assets/onprem/v2/iris-scanner-cli"
          chmod +x iris-scanner-cli
      
      - name: Run Scan 
        run: |
          $commitId = "${{ github.sha }}"
          $shortCommitId = "LinuxPR-"+$commitId.Substring(0, 8)
          $currentDirectory = (Get-Location).Path
          $solutionFile = $currentDirectory + "\Northwind.sln"
          .\iris-scanner-cli -s $currentDirectory -sln $solutionFile -r $shortCommitId