name: Linux_IRIS_Scan

on: [push, pull_request]

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
    - name: Set up JSON content
      run: |
        jsonContent=$(jq -n --arg projectId "${{ secrets.PROJECT_ID }}" --arg jwt "${{ secrets.IRIS_JWT }}" \
                    '{projectId: $projectId, jwt_auth: $jwt}')
        echo "JSON Content: $jsonContent"
        echo $jsonContent > iris.settings.json
        cat iris.settings.json
        dir