name: Windows_IRIS_Scan

# on: [push, pull_request]
on: 
  workflow_dispatch:
    inputs:
      run-job2:
        description: "Run Job"
        required: true
        default: "false"

jobs:
  scan:
    runs-on: windows-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
    
    - name: Setup .NET Core 3.1
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '3.1.100'
        
    - name: Create Settings File
      run: |
        $jsonContent = @{
          projectId = "${{ secrets.PROJECT_ID }}"
          jwt_auth = "${{ secrets.IRIS_JWT }}"
          framework = "netcore"
        } | ConvertTo-Json

        $jsonContent | Set-Content -Path "iris.settings.json"
        
    - name: Download IRIS Scanner CLI 
      shell: powershell
      run: Invoke-WebRequest -Uri "https://iris.codeeye.ai/assets/onprem/win/v1/net/iris-do.exe" -OutFile "iris-scanner-cli.exe"

    - name: Run Scan 
      shell: powershell
      run: |
        $commitId = "${{ github.sha }}"
        $shortCommitId = "PR-"+$commitId.Substring(0, 8)
        $currentDirectory = (Get-Location).Path
        $solutionFile = $currentDirectory + "\Northwind.sln"
        .\iris-scanner-cli.exe -s $currentDirectory -sln $solutionFile -r $shortCommitId
